routes/web.php
<?php

use App\Http\Controllers\Admin\JadwalVaksinasiController;
use App\Http\Controllers\Admin\JenisVaksinController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PegawaiController;
use App\Http\Controllers\Admin\VaksinatorController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Pegawai\JadwalVaksinController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::get('/',[DashboardController::class, 'index'])->name('dashboard');

    // Route Admin
    Route::resource('jenis-vaksin', JenisVaksinController::class);
    Route::resource('vaksinator', VaksinatorController::class);
    Route::resource('pegawai', PegawaiController::class);
    Route::get('jadwal-vaksinasi/{id}/peserta', [JadwalVaksinasiController::class, 'getPeserta'])->name('jadwal-vaksinasi.peserta');
    Route::delete('jadwal-vaksinasi/{id}/peserta/delete', [JadwalVaksinasiController::class, 'deletePeserta'])->name('jadwal-vaksinasi.peserta.delete');
    Route::resource('jadwal-vaksinasi', JadwalVaksinasiController::class);
    Route::put('laporan/hadir/{id}', [LaporanController::class, 'hadir'])->name('laporan.hadir');
    Route::put('laporan/tidak-hadir/{id}', [LaporanController::class, 'tidakHadir'])->name('laporan.tidak-hadir');
    Route::resource('laporan', LaporanController::class);
    
    // Route Pegawai
    Route::resource('jadwal-vaksin', JadwalVaksinController::class);
});

require __DIR__.'/auth.php';

resources/views/partials/admin/sidebar.blade.php
<aside class="aside aside-fixed">
    <div class="aside-header">
  <a href="{{ route('dashboard') }}" class="tx-montserrat tx-semibold tx-18 aside-logo">myITS Vaksin</a>
  <a href="" class="aside-menu-link">
      <i data-feather="menu"></i>
      <i data-feather="x"></i>
  </a>
</div>
<div class="aside-body">
  <ul class="nav nav-aside">
      <li class="nav-item"><a href="{{ route('dashboard') }}" class="nav-link"><i data-feather="home"></i> <span>Beranda</span></a></li>
      <li class="nav-label mg-t-15">Kelola</li>
      <li class="nav-item"><a href="{{ route('jadwal-vaksinasi.index') }}" class="nav-link"><i data-feather="calendar"></i> <span>Jadwal Vaksinasi</span></a></li>
      <li class="nav-item"><a href="{{ route('laporan.index') }}" class="nav-link"><i data-feather="clipboard"></i> <span>Laporan</span></a></li>
      <li class="nav-label mg-t-15">Data</li>
      <li class="nav-item"><a href="{{ route('pegawai.index') }}" class="nav-link"><i data-feather="user"></i> <span>Pegawai</span></a></li>
      <li class="nav-item"><a href="{{ route('vaksinator.index') }}" class="nav-link"><i data-feather="users"></i> <span>Vaksinator</span></a></li>
      <li class="nav-item"><a href="{{ route('jenis-vaksin.index') }}" class="nav-link"><i data-feather="copy"></i> <span>Jenis Vaksin</span></a></li>
  </ul>
</div>
</aside>