routes/web.php
<?php

use App\Http\Controllers\Admin\JadwalVaksinasiController;
use App\Http\Controllers\Admin\JenisVaksinController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PegawaiController;
use App\Http\Controllers\Admin\VaksinatorController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Pegawai\JadwalVaksinController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::get('/',[DashboardController::class, 'index'])->name('dashboard');

    // Route Admin
    Route::resource('jenis-vaksin', JenisVaksinController::class);
    Route::resource('vaksinator', VaksinatorController::class);
    Route::resource('pegawai', PegawaiController::class);
    Route::get('jadwal-vaksinasi/{id}/peserta', [JadwalVaksinasiController::class, 'getPeserta'])->name('jadwal-vaksinasi.peserta');
    Route::delete('jadwal-vaksinasi/{id}/peserta/delete', [JadwalVaksinasiController::class, 'deletePeserta'])->name('jadwal-vaksinasi.peserta.delete');
    Route::resource('jadwal-vaksinasi', JadwalVaksinasiController::class);
    Route::put('laporan/hadir/{id}', [LaporanController::class, 'hadir'])->name('laporan.hadir');
    Route::put('laporan/tidak-hadir/{id}', [LaporanController::class, 'tidakHadir'])->name('laporan.tidak-hadir');
    Route::resource('laporan', LaporanController::class);
    
    // Route Pegawai
    Route::resource('jadwal-vaksin', JadwalVaksinController::class);
});

require __DIR__.'/auth.php';

app/Http/Controllers/Pegawai/JadwalVaksinController.php
<?php

namespace App\Http\Controllers\Pegawai;

use Carbon\Carbon;
use App\Models\Peserta;
use Illuminate\Http\Request;
use App\Models\JadwalVaksinasi;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class JadwalVaksinController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jadwal = JadwalVaksinasi::orderBy('pelaksanaan', 'DESC')->get();
        $today = Carbon::now()->format('Y-m-d');
        return view('pages.pegawai.jadwal-vaksin.index', [
            'jadwal' => $jadwal,
            'today' => $today,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make(
            $request->all(),
            [
                'jadwal_vaksin_id' => 'required'
            ]
        );
        if($validate->fails()) {
            return back()->with('errors', $validate->message()->all()[0]->withInput());
        } else {
            $cek_vaksin = Peserta::where('pegawai_id', '=', Auth::user()->pegawai[0]->id)->count();

            if ($cek_vaksin > 0) {
                $vaksin_ke = 2;
                $tanggal_kembali = null;
            } else {
                $vaksin_ke = 1;
                $tanggal_kembali = Carbon::now()->addDays(28);
            }

            $peserta = Peserta::create([
                'jadwal_vaksin_id' => $request->jadwal_vaksin_id,
                'pegawai_id' => Auth::user()->pegawai[0]->id,
                'tanggal_vaksin' => Carbon::now(),
                'vaksin_ke' => $vaksin_ke,
                'tanggal_kembali' => $tanggal_kembali,
            ]);

            $peserta->save();
    
            if ($peserta) {
                return redirect()->route('jadwal-vaksin.index')->with('success', 'Pendaftaran vaksinasi berhasil.');
            } else {
                return back()->with('errors', 'Pendaftaran vaksinasi gagal.');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $jadwal = JadwalVaksinasi::findOrFail($id)->with(['vaksinator', 'vaksin', 'peserta'])->first();
        return view('pages.pegawai.jadwal-vaksin.show', [
            'jadwal' => $jadwal,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/admin/jadwal-vaksin/create.blade.php
@extends('layouts.base')
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30">
    <div>
      <nav aria-label="breadcrumb" class="d-none d-lg-block">
        <ol class="breadcrumb breadcrumb-style2 mg-b-10">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Beranda</a></li>
          <li class="breadcrumb-item"><a href="{{ route('jadwal-vaksinasi.index') }}">Vaksinasi Tersedia</a></li>
          <li class="breadcrumb-item active" aria-current="page">Tambah Vaksinasi</li>
        </ol>
      </nav>
      <h4 class="mg-b-0 tx-montserrat tx-medium text-truncate">
        Tambah Vaksinasi
      </h4>
    </div>
    <div class="d-lg-none mg-t-10">
    </div>
    <div>
        <a href="{{ route('jadwal-vaksinasi.index') }}"  class="btn btn-white tx-montserrat tx-semibold"><i data-feather="arrow-left" class="wd-10 mg-r-5"></i> Kembali</a>
    </div>
</div>

<div class="row row-xs">
    <div class="col-sm-12 col-lg-12 mg-b-10">
        <div class="card">
          <div class="card-body">
            <form action="{{ route('jadwal-vaksinasi.store') }}" method="POST">
                @csrf
              <p class="tx-medium tx-15">Tentang Vaksinasi Ini</p>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Vaksinator</label>
                <select class="form-control select2" name="vaksinator_id" required>
                  <option label="Pilih"></option>
                  @foreach ($vaksinators as $vaksinator)
                      <option value="{{ $vaksinator->id }}">{{ $vaksinator->nama }}</option>
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Jenis Vaksin</label>
                <select class="form-control select2" name="vaksin_id" required>
                  <option label="Pilih"></option>
                  @foreach ($vaksins as $vaksin)
                      <option value="{{ $vaksin->id }}">{{ $vaksin->nama }}</option>
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Pendaftaran dimulai</label>
                    <input type="date" id="pendaftaran_mulai" name="pendaftaran_mulai" class="form-control" required>
                  </div>
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Pendaftaran selesai</label>
                    <input type="date" id="pendaftaran_selesai" name="pendaftaran_selesai" class="form-control" required>
                  </div>
                </div>
              </div>
              <hr class="mg-t-20 mg-b-20">
              <p class="tx-medium tx-15">Pelaksanaan</p>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Tanggal Vaksinasi</label>
                <input type="date" id="pelaksanaan" name="pelaksanaan" class="form-control" required>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Sesi Vaksinasi Dimulai</label>
                    <input type="time" id="sesi_mulai" name="sesi_mulai" class="form-control" required>
                  </div>
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Sesi Vaksinasi Selesai</label>
                    <input type="time" id="sesi_selesai" name="sesi_selesai" class="form-control" required>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Lokasi</label>
                <input type="text" id="lokasi" name="lokasi" class="form-control" placeholder="Tempat vaksinasi" maxlength="100" required>
              </div>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Kuota</label>
                <input type="number" id="kuota" name="kuota" class="form-control" placeholder="Jumlah peserta" required>
              </div>
              
              <button class="btn btn-its tx-montserrat tx-semibold float-right" type="submit">Simpan</button>
            </form>
          </div>
        </div>
      </div>

</div><!-- row -->
@endsection

resources/views/pages/admin/jadwal-vaksin/edit.blade.php
@extends('layouts.base')
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30">
    <div>
      <nav aria-label="breadcrumb" class="d-none d-lg-block">
        <ol class="breadcrumb breadcrumb-style2 mg-b-10">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Beranda</a></li>
          <li class="breadcrumb-item"><a href="{{ route('jadwal-vaksinasi.index') }}">Vaksinasi Tersedia</a></li>
          <li class="breadcrumb-item active" aria-current="page">Tambah Vaksinasi</li>
        </ol>
      </nav>
      <h4 class="mg-b-0 tx-montserrat tx-medium text-truncate">
        Tambah Vaksinasi
      </h4>
    </div>
    <div class="d-lg-none mg-t-10">
    </div>
    <div>
        <a href="{{ route('jadwal-vaksinasi.index') }}"  class="btn btn-white tx-montserrat tx-semibold"><i data-feather="arrow-left" class="wd-10 mg-r-5"></i> Kembali</a>
    </div>
</div>

<div class="row row-xs">
    <div class="col-sm-12 col-lg-12 mg-b-10">
        <div class="card">
          <div class="card-body">
            <form action="{{ route('jadwal-vaksinasi.update', $jadwal->id) }}" method="POST">
                @csrf
                @method('PUT')
              <p class="tx-medium tx-15">Tentang Vaksinasi Ini</p>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Vaksinator</label>
                <select class="form-control select2" name="vaksinator_id" required>
                  <option label="Pilih"></option>
                  @foreach ($vaksinators as $vaksinator)
                      @if ($vaksinator->id == $jadwal->vaksinator_id)
                        <option value="{{ $vaksinator->id }}" selected>{{ $vaksinator->nama }}</option>                        
                      @else
                        <option value="{{ $vaksinator->id }}">{{ $vaksinator->nama }}</option>
                      @endif
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Jenis Vaksin</label>
                <select class="form-control select2" name="vaksin_id" required>
                  <option label="Pilih"></option>
                  @foreach ($vaksins as $vaksin)
                    @if ($vaksin->id == $jadwal->vaksin_id)
                      <option value="{{ $vaksin->id }}" selected>{{ $vaksin->nama }}</option>
                    @else
                      <option value="{{ $vaksin->id }}">{{ $vaksin->nama }}</option>
                    @endif
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Pendaftaran dimulai</label>
                    <input type="date" id="pendaftaran_mulai" name="pendaftaran_mulai" class="form-control" value="{{ $jadwal->pendaftaran_mulai }}" required>
                  </div>
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Pendaftaran selesai</label>
                    <input type="date" id="pendaftaran_selesai" name="pendaftaran_selesai" class="form-control" value="{{ $jadwal->pendaftaran_selesai }}" required>
                  </div>
                </div>
              </div>
              <hr class="mg-t-20 mg-b-20">
              <p class="tx-medium tx-15">Pelaksanaan</p>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Tanggal Vaksinasi</label>
                <input type="date" id="pelaksanaan" name="pelaksanaan" class="form-control" value="{{ $jadwal->pelaksanaan }}" required>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Sesi Vaksinasi Dimulai</label>
                    <input type="time" id="sesi_mulai" name="sesi_mulai" class="form-control" value="{{ $jadwal->sesi_mulai }}" required>
                  </div>
                  <div class="col-6">
                    <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Sesi Vaksinasi Selesai</label>
                    <input type="time" id="sesi_selesai" name="sesi_selesai" class="form-control" value="{{ $jadwal->sesi_selesai }}" required>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Lokasi</label>
                <input type="text" id="lokasi" name="lokasi" class="form-control" placeholder="Tempat vaksinasi" maxlength="100" value="{{ $jadwal->lokasi }}" required>
              </div>
              <div class="form-group">
                <label class="d-block tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Kuota</label>
                <input type="number" id="kuota" name="kuota" class="form-control" placeholder="Jumlah peserta" value="{{ $jadwal->kuota }}" required>
              </div>
              
              <button class="btn btn-its tx-montserrat tx-semibold float-right" type="submit">Simpan</button>
            </form>
          </div>
        </div>
      </div>

</div><!-- row -->
@endsection

resources/views/pages/admin/jadwal-vaksin/index.blade.php
@extends('layouts.base')
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30">
    <div>
      <nav aria-label="breadcrumb" class="d-none d-lg-block">
        <ol class="breadcrumb breadcrumb-style2 mg-b-10">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Beranda</a></li>
          <li class="breadcrumb-item active" aria-current="page">Jadwal Vaksinasi</li>
        </ol>
      </nav>
      <h4 class="mg-b-0 tx-montserrat tx-medium text-truncate">
        Jadwal Vaksinasi
      </h4>
    </div>
    <div class="d-lg-none mg-t-10">
    </div>
    <div>
        <a href="{{ route('jadwal-vaksinasi.create') }}"  class="btn btn-its tx-montserrat tx-semibold"><i data-feather="plus" class="wd-10 mg-r-5 tx-color-its2"></i> Tambah</a>
    </div>
</div>

<div class="row row-xs">
    <div class="col-sm-12 col-lg-12">
        <div class="card">
          <div class="card-body card-list">

            @foreach ($jadwal as $item )
              <div class="card-list-item">
                @if (\Carbon\Carbon::createFromFormat('Y-m-d', $item->pendaftaran_mulai)->isPast() && \Carbon\Carbon::createFromFormat('Y-m-d', $item->pendaftaran_selesai)->isFuture())
                  <a href="{{ route('jadwal-vaksinasi.show', $item->id) }}">
                @else
                  <a href="#">
                @endif
                  <div class="d-flex justify-content-between align-items-center sc-link">
                    <div class="media">
                      <div class="wd-40 ht-40 bg-its-icon tx-color-its mg-r-15 mg-md-r-15 d-flex align-items-center justify-content-center rounded-its"><i data-feather="calendar"></i></div>
                      <div class="media-body align-self-center">
                        <p class="tx-montserrat tx-semibold mg-b-0 tx-color-02">{{ date('l, d F Y', strtotime($item->pelaksanaan)) }}</p> 
                        <p class="tx-color-03 tx-13">{{ date('H.i', strtotime($item->sesi_mulai)) }} - {{ date('H.i', strtotime($item->sesi_selesai)) }}</p>
                        @if (\Carbon\Carbon::createFromFormat('Y-m-d', $item->pendaftaran_selesai)->isPast())
                            <span class="tx-13"><span class="tx-danger"><i class="far fa-times-circle mg-r-5"></i>Pendaftaran ditutup</span></span>
                        @elseif (\Carbon\Carbon::createFromFormat('Y-m-d', $item->pendaftaran_mulai)->isFuture())
                            <span class="tx-13"><span class="tx-gray-700"><i class="far fa-circle mg-r-5"></i>Pendaftaran belum dibuka</span></span>
                        @else
                            <span class="tx-13"><span class="tx-info"><i class="far fa-play-circle mg-r-5"></i>Pendaftaran dibuka</span></span>
                        @endif
                      </div>
                    </div>
                    <div class="btn btn-icon btn-its-icon btn-hover">
                      <i data-feather="chevron-right"></i>
                    </div>
                  </div>
                </a>
              </div>
            @endforeach
          </div>
        </div>
      </div>

</div><!-- row -->
@endsection

resources/views/pages/admin/jadwal-vaksin/show.blade.php
@extends('layouts.base')
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30">
    <div>
      <nav aria-label="breadcrumb" class="d-none d-lg-block">
        <ol class="breadcrumb breadcrumb-style2 mg-b-10">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Beranda</a></li>
          <li class="breadcrumb-item"><a href="{{ route('jadwal-vaksinasi.index') }}">Jadwal Vaksinasi</a></li>
          <li class="breadcrumb-item active" aria-current="page">Detail Vaksinasi</li>
        </ol>
      </nav>
      <h4 class="mg-b-0 tx-montserrat tx-medium text-truncate">
        Detail Vaksinasi
      </h4>
    </div>
    <div class="d-lg-none mg-t-10">
    </div>
    <div>
        <a href="{{ route('jadwal-vaksinasi.index') }}"  class="btn btn-white tx-montserrat tx-semibold"><i data-feather="arrow-left" class="wd-10 mg-r-5"></i> Kembali</a>
    </div>
</div>

<div class="row row-xs">
    <div class="col-sm-12 col-lg-12 mg-b-10">
        <div class="card">
          <div class="card-header">
            <div class="row row-xs">
              <div class="col-10 col-sm-10 col-lg-10 d-flex align-items-center">
                <div class="d-flex align-items-center">
                  <div>
                    <h5 class="tx-medium tx-montserrat mg-b-0">{{ date('l, d F Y', strtotime($jadwal->pelaksanaan)) }}</h5>
                    <p class="mg-b-5">{{ date('H.i', strtotime($jadwal->sesi_mulai)) }} - {{ date('H.i', strtotime($jadwal->sesi_selesai)) }}</p>
                    @if (\Carbon\Carbon::createFromFormat('Y-m-d', $jadwal->pendaftaran_selesai)->isPast())
                        <span class="tx-13"><span class="tx-danger"><i class="far fa-times-circle mg-r-5"></i>Pendaftaran ditutup</span></span>
                    @elseif (\Carbon\Carbon::createFromFormat('Y-m-d', $jadwal->pendaftaran_mulai)->isFuture())
                        <span class="tx-13"><span class="tx-gray-700"><i class="far fa-circle mg-r-5"></i>Pendaftaran belum dibuka</span></span>
                    @else
                        <span class="tx-13"><span class="tx-info"><i class="far fa-play-circle mg-r-5"></i>Pendaftaran dibuka</span></span>
                    @endif
                  </div>
                </div>
              </div>
              <div class="col-2 col-sm-2 col-lg-2 d-flex align-items-center justify-content-end">
                <div class="dropdown dropdown-custom">
                  <button class="btn btn-white tx-montserrat tx-semibold d-none d-lg-block" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i data-feather="more-vertical" class="wd-10 mg-r-5"></i>Pilihan
                  </button>
                  <button class="btn btn-white btn-icon d-lg-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i data-feather="more-vertical"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ route('jadwal-vaksinasi.edit', $jadwal->id) }}"><i data-feather="edit"></i>Edit</a>
                    <a class="dropdown-item btn-delete" href="#hapusvaksinasi" data-toggle="modal" data-animation="effect-scale" data-id={{ $jadwal->id }}><i data-feather="trash"></i>Hapus</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body card-list">
            <p class="tx-medium tx-15">Tentang Vaksinasi Ini</p>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Vaksinator</span> 
              <p class="mg-b-0">{{ $jadwal->vaksinator->nama }}</p>
            </div>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Jenis Vaksin</span> 
              <p class="mg-b-0">{{ $jadwal->vaksin->nama }}</p>
            </div>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Pendaftaran</span> 
              <p class="mg-b-0">{{ date('d F Y', strtotime($jadwal->pendaftaran_mulai)) }} - {{ date('d F Y', strtotime($jadwal->pendaftaran_mulai)) }}</p>
            </div>
            <hr class="mg-t-20 mg-b-20">
            <p class="tx-medium tx-15">Pelaksanaan</p>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Tanggal Vaksinasi</span> 
              <p class="mg-b-0">{{ date('d F Y', strtotime($jadwal->pelaksanaan)) }}</p>
            </div>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Sesi Vaksinasi</span> 
              <p class="mg-b-0">{{ date('H.i', strtotime($jadwal->sesi_mulai)) }} - {{ date('H.i', strtotime($jadwal->sesi_selesai)) }}</p>
            </div>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Lokasi</span> 
              <p class="mg-b-0">{{ $jadwal->lokasi }}</p>
            </div>
            <div class="card-list-text">
              <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Kuota</span> 
              <p class="mg-b-0">{{ $jadwal->kuota }} orang</p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-12 col-lg-12 mg-b-10">
        <div class="card">
          <div class="card-header">
            <div class="row row-xs">
              <div class="col-10 col-sm-10 col-lg-10 d-flex align-items-center">
                <div class="d-flex align-items-center">
                  <div>
                    <h5 class="tx-medium tx-montserrat mg-b-0">Peserta Vaksinasi</h5>
                  </div>
                </div>
              </div>
              <div class="col-2 col-sm-2 col-lg-2 d-flex align-items-center justify-content-end">
                <a href="{{ route('jadwal-vaksinasi.peserta', $jadwal->id) }}" class="btn btn-white tx-montserrat tx-semibold float-right d-none d-lg-block"><i data-feather="edit" class="wd-10 mg-r-5"></i> Edit Peserta</a>
                <a href="{{ route('jadwal-vaksinasi.peserta', $jadwal->id) }}" class="btn btn-white btn-icon tx-montserrat tx-medium float-right d-lg-none"><i data-feather="edit"></i></a>
              </div>
            </div>
          </div>
          <div class="card-body">
            <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Peserta yang sudah dipilih</span> 
            <p class="mg-b-0">{{ $jadwal->peserta->count() }} orang</p>
          </div>
        </div>
      </div>

      <div class="modal fade effect-scale" id="hapusvaksinasi" tabindex="-1" role="dialog" aria-labelledby="hapusvaksinasi" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content tx-14 bg-white">
            <div class="modal-body">
              <h5 class="tx-montserrat tx-medium">Apakah Anda yakin ingin menghapus jadwal vaksinasi ini?</h5>
              <span>Tindakan ini tidak dapat dibatalkan.</span>
            </div>
            <div class="modal-footer bd-t-0">
              <form action="{{ route('jadwal-vaksinasi.destroy', 'id') }}" method="POST">
                @method('DELETE')
                @csrf
                <input type="hidden" name="id" id="id">
                <a href="#" data-toggle="modal" data-animation="effect-scale" class="btn btn-white tx-montserrat tx-semibold" data-dismiss="modal">Batalkan</a>
                <button type="submit" class="btn btn-its tx-montserrat tx-semibold mg-l-5">Hapus</button>
              </form>
            </div>
          </div>
        </div>
      </div>

</div><!-- row -->
@endsection

@push('js')
  <script>
    $(document).on('click','.btn-delete',function(){
      let id = $(this).attr('data-id');
      $('#id').val(id);
    });
  </script>
@endpush