routes/web.php
<?php

use App\Http\Controllers\Admin\JadwalVaksinasiController;
use App\Http\Controllers\Admin\JenisVaksinController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PegawaiController;
use App\Http\Controllers\Admin\VaksinatorController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Pegawai\JadwalVaksinController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::get('/',[DashboardController::class, 'index'])->name('dashboard');

    // Route Admin
    Route::resource('jenis-vaksin', JenisVaksinController::class);
    Route::resource('vaksinator', VaksinatorController::class);
    Route::resource('pegawai', PegawaiController::class);
    Route::get('jadwal-vaksinasi/{id}/peserta', [JadwalVaksinasiController::class, 'getPeserta'])->name('jadwal-vaksinasi.peserta');
    Route::delete('jadwal-vaksinasi/{id}/peserta/delete', [JadwalVaksinasiController::class, 'deletePeserta'])->name('jadwal-vaksinasi.peserta.delete');
    Route::resource('jadwal-vaksinasi', JadwalVaksinasiController::class);
    Route::put('laporan/hadir/{id}', [LaporanController::class, 'hadir'])->name('laporan.hadir');
    Route::put('laporan/tidak-hadir/{id}', [LaporanController::class, 'tidakHadir'])->name('laporan.tidak-hadir');
    Route::resource('laporan', LaporanController::class);
    
    // Route Pegawai
    Route::resource('jadwal-vaksin', JadwalVaksinController::class);
});

require __DIR__.'/auth.php';

app/Http/Controllers/Admin/LaporanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\JadwalVaksinasi;
use App\Models\Peserta;
use Illuminate\Http\Request;

class LaporanController extends Controller
{
    public function index()
    {
        $vaksin = Peserta::with(['pegawai', 'jadwal'])->get();

        return view('pages.admin.laporan.index', [
            'vaksin' => $vaksin,
        ]);
    }

    public function show($id)
    {
        $laporan = Peserta::with(['pegawai', 'jadwal'])->findOrFail($id);

        return view('pages.admin.laporan.detail', [
            'laporan' => $laporan,
        ]);
    }

    public function hadir($id)
    {
        $peserta = Peserta::findOrFail($id);

        $peserta->update([
            'hadir' => 1,
        ]);

        if ($peserta) {
            return redirect()->route('laporan.index')->with('success', 'Peserta hadir.');
        } else {
            return back()->with('errors', 'Gagal update kehadiran peserta.');
        }
    }

    public function tidakHadir($id)
    {
        $peserta = Peserta::findOrFail($id);

        $peserta->update([
            'hadir' => 2,
        ]);

        if ($peserta) {
            return redirect()->route('laporan.index')->with('success', 'Peserta hadir.');
        } else {
            return back()->with('errors', 'Gagal update kehadiran peserta.');
        }
    }
}

resources/views/pages/admin/laporan/detail.blade.php
@extends('layouts.base')
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30">
    <div>
      <nav aria-label="breadcrumb" class="d-none d-lg-block">
        <ol class="breadcrumb breadcrumb-style2 mg-b-10">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Beranda</a></li>
          <li class="breadcrumb-item"><a href="{{ route('laporan.index') }}">Laporan</a></li>
          <li class="breadcrumb-item active" aria-current="page">Detail Laporan</li>
        </ol>
      </nav>
      <h4 class="mg-b-0 tx-montserrat tx-medium text-truncate">
        Detail Laporan
      </h4>
    </div>
    <div class="d-lg-none mg-t-10">
    </div>
    <div>
        <a href="{{ route('laporan.index') }}"  class="btn btn-white tx-montserrat tx-semibold"><i data-feather="arrow-left" class="wd-10 mg-r-5"></i> Kembali</a>
    </div>
</div>

<div class="row row-xs">
  <div class="col-sm-12 col-lg-12 mg-b-10">
    <div class="card">
      <div class="card-header">
        <div class="row row-xs">
          <div class="col-10 col-sm-10 col-lg-10 d-flex align-items-center">
            <div class="d-flex align-items-center">
              <div>
                <h5 class="tx-medium tx-montserrat mg-b-0">{{ $laporan->pegawai->users->name }}</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body card-list">
        <p class="tx-medium tx-15">Peserta Vaksinasi</p>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Nama</span> 
          <p class="mg-b-0">{{ $laporan->pegawai->users->name }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">NIK</span> 
          <p class="mg-b-0">{{ $laporan->pegawai->nik }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Kehadiran</span> 
          @if ($laporan->hadir == 0)
            <p class="mg-b-0">-</p>
          @elseif ($laporan->hadir == 1)
          @else
            <p class="mg-b-0">Tidak Hadir</p>
          @endif
        </div>
        <hr class="mg-t-20 mg-b-20">
        <p class="tx-medium tx-15">Tentang Vaksinasi Ini</p>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Vaksinator</span> 
          <p class="mg-b-0">{{ $laporan->jadwal->vaksinator->nama }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Jenis Vaksin</span> 
          <p class="mg-b-0">{{ $laporan->jadwal->vaksin->nama }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Pendaftaran</span> 
          <p class="mg-b-0">{{ date('d F Y', strtotime($laporan->jadwal->pendaftaran_mulai)) }} - {{ date('d F Y', strtotime($laporan->jadwal->pendaftaran_selesai)) }}</p>
        </div>
        <hr class="mg-t-20 mg-b-20">
        <p class="tx-medium tx-15">Pelaksanaan</p>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Tanggal Vaksinasi</span> 
          <p class="mg-b-0">{{ date('d F Y', strtotime($laporan->jadwal->pelaksanaan)) }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Sesi Vaksinasi</span> 
          <p class="mg-b-0">{{ date('H:i', strtotime($laporan->jadwal->sesi_mulai)) }} - {{ date('H:i', strtotime($laporan->jadwal->sesi_selesai)) }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Lokasi</span> 
          <p class="mg-b-0">{{ $laporan->jadwal->lokasi }}</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Kuota</span> 
          <p class="mg-b-0">{{ $laporan->jadwal->kuota }} orang</p>
        </div>
        <div class="card-list-text">
          <span class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase tx-semibold">Vaksinasi Ke</span> 
          <p class="mg-b-0">{{ $laporan->vaksin_ke }}</p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-lg-12 mg-b-10">
    <div class="card">
      <div class="card-header">
        <div class="row row-xs">
          <div class="col-10 col-sm-10 col-lg-10 d-flex align-items-center">
            <div class="d-flex align-items-center">
              <div>
                <h5 class="tx-medium tx-montserrat mg-b-0">KIPI</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body pd-0">
        <div class="table-responsive">
          <table class="table table-borderless table-hover">
            <thead>
              <tr class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase">
                <th class="wd-15p th-its">Tanggal Kejadian</th>
                <th class="wd-40p th-its">Gejala</th>
                <th class="wd-30p th-its">Tindakan</th>
                <th class="wd-15p th-its">Hubungi Dokter</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="td-its tx-medium align-middle border-bottom">20 Mar 2021</td>
                <td class="td-its align-middle border-bottom">Pilek</td>
                <td class="td-its align-middle border-bottom">Obat pilek</td>
                <td class="td-its align-middle border-bottom">Sudah</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div><!-- row -->
@endsection

@section('modal')
<div class="modal fade effect-scale" id="editkehadiran" tabindex="-1" role="dialog" aria-labelledby="modalmyfile" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="tx-montserrat tx-medium" id="editkehadiranLabel">Edit Kehadiran</h5>
      </div>
      <form>
        <div class="modal-body pd-t-0">
          <div class="form-group">
            <div class="row">
              <div class="col-4">
                <div class="custom-control custom-radio">
                  <input type="radio" id="hadir_ya" name="is_hadir" class="custom-control-input" required>
                  <label class="custom-control-label" for="hadir_ya">Hadir</label>
                </div>
              </div>
              <div class="col-4">
              <div class="custom-control custom-radio">
                  <input type="radio" id="hadir_tidak" name="is_hadir" class="custom-control-input">
                  <label class="custom-control-label" for="hadir_tidak">Tidak hadir</label>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-white tx-montserrat tx-semibold" data-dismiss="modal">Batalkan</button>
          <button type="submit" class="btn btn-its tx-montserrat tx-semibold mg-l-5">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>
  
@endsection

resources/views/pages/admin/laporan/index.blade.php
@extends('layouts.base')
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30">
    <div>
      <nav aria-label="breadcrumb" class="d-none d-lg-block">
        <ol class="breadcrumb breadcrumb-style2 mg-b-10">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Beranda</a></li>
          <li class="breadcrumb-item active" aria-current="page">Laporan</li>
        </ol>
      </nav>
      <h4 class="mg-b-0 tx-montserrat tx-medium text-truncate">
        Laporan
      </h4>
    </div>
    <div class="d-lg-none mg-t-10">
    </div>
    <div>
    </div>
</div>

<div class="row row-xs">
    <div class="col-sm-12 col-lg-12">
        <div class="card">
          <div class="card-body pd-0 table-responsive">
            <table id="example1" class="table table-borderless mg-0">
              <thead>
                <tr class="tx-10 tx-spacing-1 tx-color-03 tx-uppercase">
                  <th class="wd-25p th-its" style="border-bottom: none !important"><span>Pegawai</span></th>
                  <th class="wd-20p th-its" style="border-bottom: none !important"><span>Kehadiran</span></th>
                  <th class="wd-5p th-its" style="border-bottom: none !important"><span>Vaksinasi Ke</span></th>
                  <th class="wd-10p th-its" style="border-bottom: none !important"><span>Vaksinasi Pada</span></th>
                  <th class="wd-10p th-its" style="border-bottom: none !important"><span>Vaksinasi Selanjutnya</span></th>
                  <th class="wd-20p th-its" style="border-bottom: none !important"><span>Vaksinator</span></th>
                  <th class="wd-10p th-its" style="border-bottom: none !important"><span>Penyelenggara</span></th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($vaksin as $item)
                      <tr>
                        <td class="td-its align-middle border-bottom">
                            <a href="{{ route('laporan.show', $item->id) }}">
                              <p class="mg-b-0 tx-medium tx-color-its3">{{ $item->pegawai->users->name }}</p>
                              <p class="mg-b-0 tx-13 tx-color-03">{{ $item->pegawai->nik }}</p>
                            </a>
                          </td>
                          @if ($item->hadir == 0)
                          <td class="td-its align-middle border-bottom d-flex align-items-center">
                              <form action="{{ route('laporan.hadir', $item->id) }}" method="POST">
                                @csrf
                                @method('PUT')
                                <button class="btn btn-white btn-icon" type="submit" data-toggle="tooltip" data-placement="bottom" title="Hadir"><i class="fas fa-check-circle tx-success"></i></button>
                              </form>
                              <form action="{{ route('laporan.tidak-hadir', $item->id) }}" class="mg-l-5" method="POST">
                                @csrf
                                @method('PUT')
                                <button class="btn btn-white btn-icon" type="submit" data-toggle="tooltip" data-placement="bottom" title="Tidak hadir"><i class="fas fa-times-circle tx-danger"></i></button>
                              </form>
                            @elseif ($item->hadir == 1)
                            <td class="td-its align-middle border-bottom align-items-center">
                                <span class="tx-color-01"><i class="fas fa-check-circle mg-r-5 tx-success"></i>Hadir</span>
                            @else
                            <td class="td-its align-middle border-bottom align-items-center">
                                <span class="tx-color-01"><i class="fas fa-times-circle mg-r-5 tx-danger"></i>Tidak hadir</span>
                            @endif
                          </td>
                          <td class="td-its align-middle border-bottom tx-color-02">{{ $item->vaksin_ke }}</td>
                          <td class="td-its align-middle border-bottom tx-color-02">{{ date('d/m/Y', strtotime($item->tanggal_vaksin)) }}</td>
                          <td class="td-its align-middle border-bottom tx-color-02">{{ $item->tanggal_kembali ? date('d/m/Y', strtotime($item->tanggal_kembali)) : '-' }}</td>
                          <td class="td-its align-middle border-bottom tx-color-02">{{ $item->jadwal->vaksinator->nama }}</td>
                          <td class="td-its align-middle border-bottom tx-color-02">{{ $item->jadwal->penyelenggara }}</td>        
                      </tr>
                  @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>

</div><!-- row -->
@endsection

@push('js')
    <script>
        $(function(){
        'use strict'

        $('#example1').DataTable({
            language: {
            searchPlaceholder: 'Cari',
            sSearch: '',
            lengthMenu: '_MENU_ data/halaman',
            emptyTable:         'Tidak ada data yang tersedia pada tabel ini',
            zeroRecords:        'Tidak ditemukan data yang sesuai',
            info:               'Menampilkan _START_ sampai _END_ dari _TOTAL_ entri',
            infoEmpty:          'Menampilkan 0 sampai 0 dari 0 entri',
            infoFiltered:       '(disaring dari _MAX_ entri keseluruhan)',
            paginate: {
                first: "<i class='fas fa-angle-double-left'></i>",
                last: "<i class='fas fa-angle-double-right'></i>",
                previous: "<i class='fas fa-angle-left'></i>",
                next: "<i class='fas fa-angle-right'></i>"
            },
            }
        });

          // Select2
          $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

        });
    </script>
@endpush